---
#### update nodes
- name: confirm whether user really meant to update servers
  hosts: all
  gather_facts: false

  vars_prompt:
    - name: ireallymeanit
      prompt: Are you sure you want to update each node ?
      default: 'no'
      private: no

  tasks:
  - name: exit playbook, if user did not mean to update servers
    fail:
      msg: >
        "Exiting update-server playbook, servers were NOT updated.
         To update servers, either say 'yes' on the prompt or
         or use `-e ireallymeanit=yes` on the command line when
         invoking the playbook"
    when: ireallymeanit != 'yes'

- hosts: update
  roles:
  - role: node-update