#### perform minor os updates/upgrades
- include: os-updates/update-ubuntu.yml
  when: ansible_distribution == 'Ubuntu'

- include: os-updates/update-rocky.yml
  when: ansible_distribution == 'Rocky'

## performs upgrades of zfs packages

- include: package-updates/45drives-zfs-ubuntu.yml
  when: (ansible_distribution == 'Ubuntu') and (zfs_updates == true)

- include: package-updates/45drives-zfs-rocky.yml
  when: (ansible_distribution == 'Rocky') and (zfs_updates == true)

## performs upgrades of ceph packages

- include: package-updates/45drives-ceph-ubuntu.yml
  when: (ansible_distribution == 'Ubuntu') and (ceph_updates == true)

- include: package-updates/45drives-ceph-rocky.yml
  when: (ansible_distribution == 'Rocky') and (ceph_updates == true)

## performs upgrades of 45drives packages

- include: package-updates/45drives-packages-ubuntu.yml
  when: (ansible_distribution == 'Ubuntu') and (houston_updates == true)

- include: package-updates/45drives-packages-rocky.yml
  when: (ansible_distribution == 'Rocky') and (houston_updates == true)
