- name: apt update ubuntu
  apt:
      update-cache: yes

- name: check upgrade available packages for ubuntu
  apt:
      upgrade: yes
  check_mode: true
  register: upgradable

- name: list upgrade available packages for ubuntu
  debug:
    msg: "{{ upgradable }}"

- name: apt upgrade ubuntu
  apt:
      upgrade: yes
      autoremove: yes
      autoclean: yes

- name: check if reboot required for ubuntu
  stat:
    path: /var/run/reboot-required
  register: reboot_yes

- name: rebooting ubuntu
  reboot:
    reboot_timeout: 600
  when: reboot_yes.stat.exists