- name: apt update ubuntu
  apt:
      update-cache: yes

- name: check upgrade available packages for ubuntu
  apt:
      upgrade: yes
      name: "45drives-tools"
  check_mode: true
  register: upgradable

- name: list upgrade available packages for ubuntu
  debug:
    msg: "{{ upgradable }}"

- name: apt upgrade ubuntu
  apt:
      upgrade: yes
      name: "45drives-tools"
      only_upgrade: yes
      update_cache: yes
      autoremove: yes
      autoclean: yes
