- name: check ubuntu zfs packages available for update
  apt:
      list: updates
      name: "zfs"
      name: "zfsutils-linux"
      name: "libzfs2linux"
      name: "libzfslinux-dev"
  register: upgradable

- name: list upgrade available packages for rocky linux
  debug:
    msg: "{{ upgradable }}"

- name: update ubuntu zfs
  apt:
      name: "zfs"
      name: "zfsutils-linux"
      name: "libzfs2linux"
      name: "libzfslinux-dev"
      state: latest
      only_upgrade: yes
      update_cache: yes
      autoremove: yes
      autoclean: yes