- name: check rocky linux packages available for update
  dnf:
      list: updates
      name: "45drives-tools"
      name: "cockpit*"
      name: "cephgeorep"
  register: upgradable

- name: list upgrade available packages for rocky linux
  debug:
    msg: "{{ upgradable }}"

- name: update rocky linux
  dnf:
      name: "45drives-tools"
      name: "cockpit*"
      name: "cephgeorep"
      state: latest
      update_only: yes
      update_cache: yes
