- name: check rocky linux packages available for update
  dnf:
     list: updates
  register: upgradable

- name: list upgrade available packages for rocky linux
  debug:
    msg: "{{ upgradable }}"
 
- name: display count of updates for rocky linux
  debug:
    msg: "Found {{ upgradable | length }} packages to be updated:\n\n{{ upgradable }}"

- name: update rocky linux
  dnf:
      name: "*"
      exclude: '"zfs" "ceph*" "45drives-tools" "cockpit*"'
      state: latest
      update_cache: true

- name: check if reboot required for rocky
  shell: dnf needs-restarting -r
  failed_when: false
  register: reboot_yes
  changed_when: false

- name: rebooting rocky
  reboot:
    reboot_timeout: 600
  when: (reboot_yes.rc != 0) and (perform_reboot == true)