- name: check upgrade available packages for ubuntu
  apt:
      name: "*"
      state: latest
      update-cache: yes
      autoremove: yes
      autoclean: yes
  check_mode: true
  register: upgradable

- name: list upgrade available packages for ubuntu
  debug:
    msg: "{{ upgradable }}"

- name: hold ceph/zfs/45drives packages back from apt update apt upgrade
  dpkg_selections:
      name: ceph*
      selection: hold
  dpkg_selections:
      name: zfs-dkms
      selection: hold
  dpkg_selections:
      name: zfsutils-linux
      selection: hold
  dpkg_selections:
      name: libzfs2linux
      selection: hold
  dpkg_selections:
      name: zfs-zed
      selection: hold
  dpkg_selections:
      name: 45drives-tools
      selection: hold
  dpkg_selections:
      name: cockpit*
      selection: hold
  dpkg_selections:
      name: cephgeorep
      selection: hold
  

- name: apt update apt upgrade ubuntu
  apt:
      name: "*"
      state: latest
      update-cache: yes
      autoremove: yes
      autoclean: yes

- name: check if reboot required for ubuntu
  stat:
    path: /var/run/reboot-required
  register: reboot_yes

- name: rebooting ubuntu
  reboot:
    reboot_timeout: 600
  when: (reboot_yes.stat.exists) and (perform_reboot == true)