- name: check rocky linux packages available for update
  dnf:
     list: updates
  register: upgradable

- name: list upgrade available packages for rocky linux
  debug:
    msg: "{{ upgradable }}"
 
- name: display count of updates for rocky linux
  debug:
    msg: "Found {{ upgradable | length }} packages to be updated:\n\n{{ upgradable }}"

- name: update rocky linux
  dnf:
      name: "*"
      state: latest
      update_cache: true